version: '3'

volumes:
  ptolemay_test_assigment_local_postgres_data: { }
  ptolemay_test_assigment_local_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ptolemay_test_assigment_django
    container_name: ptolemay_test_assignment_local
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/local/postgres/Dockerfile
    image: ptolemay_test_assignment_postgres
    container_name: ptolemay_test_assigment_local_postgres
    volumes:
      - ptolemay_test_assigment_local_postgres_data:/var/lib/postgresql/data
      - ptolemay_test_assigment_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
