# Generated by Django 4.1.9 on 2023-06-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
